@props([
    'supplier' => null,
    'partyTypes' => [],
    'deliveryModes' => [],
    'supplierTypes' => [],
    'supplierTypeFlags' => [],
    'designations' => [],
    'categories' => [],
    // Filtered by party type; reloaded from the agents endpoint when it changes.
    'agents' => [],
    // Agent id => {type, value} from Agent Master — commission fields are read-only.
    'agentCommissions' => [],
    'countries' => [],
    // Change request #4 — "Default the Country to India".
    'indiaCountryId' => null,
    // Rendered server-side for the country/state already chosen; the cascade
    // reloads them from GeoController once a parent changes.
    'states' => [],
    'cities' => [],
])

@php
    /**
     * Supplier form — every field on the client's Supplier Master sheet, in the
     * sheet's own order, plus the party-type and jobwork fields from
     * DATABASE_SCHEMA.md §5. Column letters are noted against each field.
     *
     * Laid out one field per line, label on the left, grouped into sections —
     * same as Category, Product and Buyer. 27 columns in a flat grid is
     * unreadable.
     *
     * Three fields are conditional, and each is hidden rather than disabled so
     * the browser stops posting it at all; the request re-applies the same
     * condition server-side, so the JavaScript is a courtesy, not the rule:
     *
     *   col E  GST Number  — only when the chosen supplier type is registered
     *   col G  MSME reg no — only when "MSME registered" is ticked
     *   jobwork section    — only when the party type is Jobber or Both
     */

    // Categories already linked, for the multi-select (col R).
    $selectedCategories = $supplier?->categories->pluck('id')->all() ?? [];

    // Cols H–K live in supplier_contacts as the row flagged primary.
    $primary = $supplier?->contacts->firstWhere('is_primary', true);

    /**
     * Col L — "other contact persons". Everyone except the primary, or one
     * blank row to start from. Old input wins so a failed round-trip keeps
     * whatever the user had typed.
     */
    $extraContacts = old('contacts');

    if ($extraContacts === null) {
        $extraContacts = $supplier
            ? $supplier->contacts->where('is_primary', false)->map(fn ($c) => [
                'name'           => $c->name,
                'designation_id' => $c->designation_id,
                'mobile'         => $c->mobile,
                'email'          => $c->email,
            ])->values()->all()
            : [];
    }

    if ($extraContacts === []) {
        $extraContacts = [['name' => null, 'designation_id' => null, 'mobile' => null, 'email' => null]];
    }

    /**
     * Whether the Secondary Contact Person section starts open. Same
     * reasoning as the Buyer form's $secondaryContactsVisible.
     */
    $secondaryContactsVisible = old('contacts') !== null
        || ($supplier?->contacts->where('is_primary', false)->isNotEmpty() ?? false);

    /**
     * Initial visibility of the three conditional blocks, decided here rather
     * than left to the script below.
     *
     * If the server renders them all open and JavaScript closes them on load,
     * every edit of a trading supplier flashes a GST field that does not apply
     * before taking it away again. The script still owns what happens when the
     * user changes the field it depends on; this is only the starting state.
     *
     * A block holding a rejected value stays open either way — the error
     * message would otherwise be hidden along with the field it belongs to.
     */
    $selectedType = old('supplier_type_id', $supplier?->supplier_type_id);

    $gstVisible = ($supplierTypeFlags[$selectedType] ?? false) === true
        || $errors->has('gst_number');

    $msmeVisible = (bool) old('is_msme', $supplier?->is_msme)
        || $errors->has('msme_registration_no');

    $jobworkVisible = in_array(
        old('party_type', $supplier?->party_type ?? 'supplier'),
        ['jobber', 'both'],
        true
    );
@endphp

{{-- ================== A–C · IDENTIFICATION ======================= --}}
<x-ui.form-section title="Identification" icon="bi-truck"
                   subtitle="Who the party is, and whether we buy their labour or their goods.">
    <div class="form-stack">

        {{-- Col A — "it should tell me if a certain code is used already".
             Typed, not autogenerated: Category and Product get a CAT001 from
             the number series, this one the user chooses. --}}
        <div class="row form-line">
            <label for="display_code" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                Display Code <span class="req">*</span>
            </label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group">
                    <span class="input-group-text bg-body-secondary"><i class="bi bi-hash"></i></span>
                    <input type="text" id="display_code" name="display_code" maxlength="5" required
                           value="{{ old('display_code', $supplier?->display_code) }}"
                           class="form-control font-monospace text-uppercase @error('display_code') is-invalid @enderror"
                           placeholder="SUP01" autocomplete="off">
                </div>
                @error('display_code')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                {{-- Rewritten by JS only once a code has actually been checked. --}}
                <div class="form-text js-code-feedback">Up to 5 characters. Must be unique.</div>
            </div>
        </div>

        {{-- Not on the sheet — DATABASE_SCHEMA.md §5. Jobber and Supplier share
             this table; this column is what tells them apart, and it decides
             which agents are offered below and whether the jobwork section
             applies. --}}
        <x-ui.select name="party_type" label="Party Type" required horizontal
                     :options="$partyTypes"
                     :selected="$supplier?->party_type ?? 'supplier'"
                     :placeholder="false"
                     data-cascade-child="#agent_id"
                     hint="Jobwork means we supply the material and buy the making. Trading means we buy finished goods." />

        {{-- Col B --}}
        <x-ui.field name="company_name" label="Company Name" :value="$supplier?->company_name" required
                    horizontal maxlength="200" placeholder="Sri Garments" />

        {{-- Col C — the name on the purchase bill is not always the trading name --}}
        <x-ui.field name="name_on_bill" label="Name on Bill" :value="$supplier?->name_on_bill"
                    horizontal maxlength="200" placeholder="Exactly as it prints on their invoice"
                    hint="Leave blank to use the company name." />

        {{-- Col R — "drop down menu with a search bar menu, allow multiple to
             be chosen". Categories, not products: the client's own example
             values are category names, and Jobber Q1 is explicit about it. --}}
        <x-ui.select name="category_ids" label="Product Category"
                     :options="$categories" :selected="$selectedCategories"
                     horizontal searchable multiple
                     placeholder="Search categories…"
                     hint="A jobber usually makes one category; a trading supplier one or two." />

    </div>
</x-ui.form-section>

{{-- ================ D–G · TAX & REGISTRATION ===================== --}}
<x-ui.form-section title="Tax & Registration" icon="bi-file-earmark-check"
                   subtitle="Decides what can be claimed on their purchase bill.">
    <div class="form-stack">

        {{-- Col D — "(composition) give option to add more in the future".
             A lookup table, so a new type does not need a migration. Typing a
             name not already in the list adds it, same quick-add pattern as
             the Buyer form's Payment Terms / Designation fields. --}}
        <x-ui.select name="supplier_type_id" label="Supplier Type" :options="$supplierTypes"
                     :selected="$supplier?->supplier_type_id" horizontal searchable
                     placeholder="Search or type to add a new type…"
                     data-create-url="{{ route('masters.suppliers.supplier-types.store') }}"
                     hint="Registered types are asked for a GST number." />

        {{-- Col E — "only if the registered option is chosen". Hidden, not
             disabled: a hidden field is not submitted at all, and the request
             blanks it server-side for the same case. --}}
        <div class="row form-line @unless($gstVisible) d-none @endunless" id="gst-row">
            <label for="gst_number" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                GST Number <span class="req">*</span>
            </label>
            <div class="col-sm-8 col-lg-9">
                <input type="text" id="gst_number" name="gst_number" maxlength="15"
                       value="{{ old('gst_number', $supplier?->gst_number) }}"
                       class="form-control font-monospace text-uppercase @error('gst_number') is-invalid @enderror"
                       placeholder="33ABCDE1234F1Z5" autocomplete="off">
                @error('gst_number')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">15 characters. Contains the PAN below at positions 3–12.</div>
            </div>
        </div>

        {{-- Col F --}}
        <x-ui.field name="pan_number" label="PAN Number" :value="$supplier?->pan_number"
                    horizontal maxlength="10" placeholder="ABCDE1234F"
                    class="font-monospace text-uppercase" />

        {{-- Col G — "to appear to put in the msme registration details". The
             yes/no is its own answer; a blank number is not the same as "no". --}}
        <div class="row form-line">
            <label class="col-sm-4 col-lg-3 col-form-label fw-semibold">MSME</label>
            <div class="col-sm-8 col-lg-9 pt-2">
                <div class="form-check">
                    {{-- An unticked checkbox posts nothing, so the hidden field
                         carries the "no" that would otherwise be silence. --}}
                    <input type="hidden" name="is_msme" value="0">
                    <input type="checkbox" class="form-check-input" id="is_msme" name="is_msme" value="1"
                           @checked(old('is_msme', $supplier?->is_msme))>
                    <label class="form-check-label" for="is_msme">This supplier is MSME registered</label>
                </div>
            </div>
        </div>

        <div class="row form-line @unless($msmeVisible) d-none @endunless" id="msme-row">
            <label for="msme_registration_no" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                MSME Registration No <span class="req">*</span>
            </label>
            <div class="col-sm-8 col-lg-9">
                <input type="text" id="msme_registration_no" name="msme_registration_no" maxlength="40"
                       value="{{ old('msme_registration_no', $supplier?->msme_registration_no) }}"
                       class="form-control font-monospace text-uppercase @error('msme_registration_no') is-invalid @enderror"
                       placeholder="UDYAM-TN-33-0001234" autocomplete="off">
                @error('msme_registration_no')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">MSME dues carry a statutory 45-day payment limit — this drives that check later.</div>
            </div>
        </div>

    </div>
</x-ui.form-section>

{{-- ================== H–K · PRIMARY CONTACT ====================== --}}
<x-ui.form-section title="Primary Contact" icon="bi-person-lines-fill"
                   subtitle="The person we deal with. Saved alongside the extra contacts below.">
    <div class="form-stack">

        {{-- Col H --}}
        <x-ui.field name="contact_name" label="Name" :value="$primary?->name"
                    horizontal maxlength="120" placeholder="Ramesh" />

        {{-- Col I — "search bar and option to add a new one in the future".
             A lookup rather than free text, or three spellings of
             "Merchandiser" arrive within a month. --}}
        <x-ui.select name="contact_designation_id" label="Designation" :options="$designations"
                     :selected="$primary?->designation_id" horizontal searchable
                     placeholder="Search designation…" />

        {{-- Col J --}}
        <x-ui.field name="contact_email" label="Email" type="email" :value="$primary?->email"
                    horizontal maxlength="150" placeholder="ramesh@srigarments.com" />

        {{-- Col K --}}
        <x-ui.field name="contact_mobile" label="Mobile" :value="$primary?->mobile"
                    horizontal maxlength="30" placeholder="9876543210" />

    </div>
</x-ui.form-section>

{{-- ================ L · SECONDARY CONTACT PERSON ==================== --}}
<x-ui.form-section title="Secondary Contact Person" icon="bi-people"
                   subtitle="Sheet col L — name, designation and phone number for each additional person.">

    <div class="form-check mb-3">
        <input type="checkbox" class="form-check-input" id="toggle-secondary-contacts"
               @checked($secondaryContactsVisible)>
        <label class="form-check-label" for="toggle-secondary-contacts">Add a secondary contact person</label>
    </div>

    <div id="secondary-contacts-wrap" class="{{ $secondaryContactsVisible ? '' : 'd-none' }}">
    {{-- One header row rather than the same four labels repeated per person,
         same as the incentives grid on the Product master. --}}
    <div class="table-responsive">
        <table class="table grid-table align-middle mb-0">
            <thead>
                <tr>
                    <th style="min-width:180px">Name</th>
                    <th style="min-width:180px">Designation</th>
                    <th style="min-width:150px">Mobile</th>
                    <th style="min-width:200px">Email</th>
                    <th style="width:40px"></th>
                </tr>
            </thead>
            <tbody id="contact-rows">
                @foreach($extraContacts as $index => $row)
                    <tr data-contact-row>
                        <td>
                            <input type="text" maxlength="120"
                                   name="contacts[{{ $index }}][name]"
                                   value="{{ $row['name'] ?? '' }}"
                                   class="form-control form-control-sm @error("contacts.{$index}.name") is-invalid @enderror"
                                   placeholder="Full name" aria-label="Contact name">
                            @error("contacts.{$index}.name")<div class="cell-error">{{ $message }}</div>@enderror
                        </td>
                        <td>
                            <select name="contacts[{{ $index }}][designation_id]"
                                    class="form-select form-select-sm @error("contacts.{$index}.designation_id") is-invalid @enderror"
                                    data-searchable data-placeholder="Designation…" aria-label="Designation">
                                <option value="">— Select —</option>
                                @foreach($designations as $id => $name)
                                    <option value="{{ $id }}" @selected((string) ($row['designation_id'] ?? '') === (string) $id)>{{ $name }}</option>
                                @endforeach
                            </select>
                            @error("contacts.{$index}.designation_id")<div class="cell-error">{{ $message }}</div>@enderror
                        </td>
                        <td>
                            <input type="text" maxlength="30"
                                   name="contacts[{{ $index }}][mobile]"
                                   value="{{ $row['mobile'] ?? '' }}"
                                   class="form-control form-control-sm @error("contacts.{$index}.mobile") is-invalid @enderror"
                                   placeholder="9876543210" aria-label="Mobile">
                            @error("contacts.{$index}.mobile")<div class="cell-error">{{ $message }}</div>@enderror
                        </td>
                        <td>
                            <input type="email" maxlength="150"
                                   name="contacts[{{ $index }}][email]"
                                   value="{{ $row['email'] ?? '' }}"
                                   class="form-control form-control-sm @error("contacts.{$index}.email") is-invalid @enderror"
                                   placeholder="name@company.com" aria-label="Email">
                            @error("contacts.{$index}.email")<div class="cell-error">{{ $message }}</div>@enderror
                        </td>
                        <td class="text-end">
                            <button type="button" class="btn btn-sm btn-link text-danger p-0 js-remove-contact"
                                    aria-label="Remove contact" data-bs-toggle="tooltip" title="Remove contact">
                                <i class="bi bi-x-lg"></i>
                            </button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <button type="button" class="btn btn-sm btn-outline-secondary mt-2" id="add-contact">
        <i class="bi bi-plus-lg me-1"></i>Add contact
    </button>
    <div class="form-text">Rows with no name are not saved.</div>
    </div>{{-- /#secondary-contacts-wrap --}}

    {{-- Cloned by the Add button. Inside a template so the searchable select in
         it is not picked up by the page-load TomSelect sweep — a pre-initialised
         clone renders as a dead widget. --}}
    <template id="contact-row-template">
        <tr data-contact-row>
            <td>
                <input type="text" maxlength="120" name="contacts[__INDEX__][name]"
                       class="form-control form-control-sm" placeholder="Full name" aria-label="Contact name">
            </td>
            <td>
                <select name="contacts[__INDEX__][designation_id]" class="form-select form-select-sm"
                        data-searchable data-placeholder="Designation…" aria-label="Designation">
                    <option value="">— Select —</option>
                    @foreach($designations as $id => $name)
                        <option value="{{ $id }}">{{ $name }}</option>
                    @endforeach
                </select>
            </td>
            <td>
                <input type="text" maxlength="30" name="contacts[__INDEX__][mobile]"
                       class="form-control form-control-sm" placeholder="9876543210" aria-label="Mobile">
            </td>
            <td>
                <input type="email" maxlength="150" name="contacts[__INDEX__][email]"
                       class="form-control form-control-sm" placeholder="name@company.com" aria-label="Email">
            </td>
            <td class="text-end">
                <button type="button" class="btn btn-sm btn-link text-danger p-0 js-remove-contact"
                        aria-label="Remove contact">
                    <i class="bi bi-x-lg"></i>
                </button>
            </td>
        </tr>
    </template>
</x-ui.form-section>

{{-- ==================== M–Q · ADDRESS =========================== --}}
<x-ui.form-section title="Address" icon="bi-geo-alt"
                   subtitle="Prints on the purchase order and the material issue note.">
    <div class="form-stack">

        {{-- Col M --}}
        <x-ui.textarea name="address" label="Address" :value="$supplier?->address"
                       horizontal rows="2" maxlength="255" placeholder="12 SIPCOT" />

        {{-- Cols P, O, N — Country, State, City.

             Ordered parent-first, which is the reverse of the sheet's own
             N, O, P. A dependent dropdown that sits above the field it depends
             on reads as broken: the user tabs into "City", finds it empty, and
             has no way to tell the answer is two rows further down.

             The three cascade, and both children are re-checked against their
             parent on submit — see SupplierRequest. --}}
        <x-ui.select name="country_id" label="Country" :options="$countries"
                     :selected="$supplier?->country_id ?? $indiaCountryId" horizontal searchable
                     placeholder="Search country…"
                     data-cascade-child="#state_id" />

        {{-- Col O --}}
        <x-ui.select name="state_id" label="State" :options="$states"
                     :selected="$supplier?->state_id" horizontal searchable
                     placeholder="Search state…"
                     data-cascade-child="#city_id"
                     data-cascade-parent="#country_id"
                     :data-cascade-url="route('masters.geo.states')"
                     data-cascade-key="country_id"
                     data-cascade-empty="Select a country first" />

        {{-- Col N --}}
        <x-ui.select name="city_id" label="City" :options="$cities"
                     :selected="$supplier?->city_id" horizontal searchable
                     placeholder="Search city…"
                     data-cascade-parent="#state_id"
                     :data-cascade-url="route('masters.geo.cities')"
                     data-cascade-key="state_id"
                     data-cascade-empty="Select a state first" />

        {{-- Col Q --}}
        <x-ui.field name="pincode" label="PIN Code" :value="$supplier?->pincode"
                    horizontal maxlength="20" placeholder="641601" />

    </div>
</x-ui.form-section>

{{-- =================== S–T · TRADE TERMS ======================== --}}
<x-ui.form-section title="Trade Terms" icon="bi-percent"
                   subtitle="Their discount and credit period. The discount feeds the cost build-up on a quotation.">
    <div class="form-stack">

        {{-- Col S — "maximum 2 characters allowed", so 0–99. --}}
        <div class="row form-line">
            <label for="discount_percent" class="col-sm-4 col-lg-3 col-form-label fw-semibold">Discount %</label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group" style="max-width:220px">
                    <input type="number" step="0.01" min="0" max="99.99"
                           id="discount_percent" name="discount_percent"
                           value="{{ old('discount_percent', $supplier?->discount_percent) }}"
                           class="form-control @error('discount_percent') is-invalid @enderror"
                           placeholder="0.00">
                    <span class="input-group-text">%</span>
                </div>
                @error('discount_percent')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">Taken off their rate before our markup is added.</div>
            </div>
        </div>

        {{-- Col T — "maximum 3 characters allowed", so 0–999 days. Stored as a
             number, not the sheet's "45 Days", because the due date is computed
             from it. 0 means paid on dispatch, which is what most jobbers take. --}}
        <div class="row form-line">
            <label for="credit_days" class="col-sm-4 col-lg-3 col-form-label fw-semibold">Credit Terms</label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group" style="max-width:220px">
                    <input type="number" step="1" min="0" max="999"
                           id="credit_days" name="credit_days"
                           value="{{ old('credit_days', $supplier?->credit_days) }}"
                           class="form-control @error('credit_days') is-invalid @enderror"
                           placeholder="45">
                    <span class="input-group-text">days</span>
                </div>
                @error('credit_days')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">Enter 0 for payment on dispatch. Trading suppliers are usually 30–45.</div>
            </div>
        </div>

    </div>
</x-ui.form-section>

{{-- ================ JOBWORK (schema §5, not on the sheet) ======== --}}
{{-- The class has to be bound, not written as a directive inside the attribute:
     Blade compiles directives in plain markup but passes a component tag's
     attribute values through as literal strings. --}}
<x-ui.form-section title="Jobwork" icon="bi-tools" id="jobwork-section"
                   :class="$jobworkVisible ? '' : 'd-none'"
                   subtitle="Applies to a jobber. We supply the material and buy the making.">
    <div class="form-stack">

        <div class="row form-line">
            <label class="col-sm-4 col-lg-3 col-form-label fw-semibold">Material</label>
            <div class="col-sm-8 col-lg-9 pt-2">
                <div class="form-check">
                    <input type="hidden" name="we_supply_material" value="0">
                    <input type="checkbox" class="form-check-input" id="we_supply_material"
                           name="we_supply_material" value="1"
                           @checked(old('we_supply_material', $supplier?->we_supply_material))>
                    <label class="form-check-label" for="we_supply_material">
                        We supply the material — fabric, trims, labels, packing
                    </label>
                </div>
                <div class="form-text">Switches on Material Issue against this party.</div>
            </div>
        </div>

        <div class="row form-line">
            <label class="col-sm-4 col-lg-3 col-form-label fw-semibold">Sample</label>
            <div class="col-sm-8 col-lg-9 pt-2">
                <div class="form-check">
                    <input type="hidden" name="requires_sample_approval" value="0">
                    <input type="checkbox" class="form-check-input" id="requires_sample_approval"
                           name="requires_sample_approval" value="1"
                           @checked(old('requires_sample_approval', $supplier?->requires_sample_approval))>
                    <label class="form-check-label" for="requires_sample_approval">
                        A sample must be approved before a PO is raised
                    </label>
                </div>
            </div>
        </div>

    </div>
</x-ui.form-section>

{{-- ================ DELIVERY (schema §5 Q13) ===================== --}}
<x-ui.form-section title="Delivery" icon="bi-box-arrow-right">
    <div class="form-stack">
        <x-ui.select name="default_delivery_mode" label="Default Delivery Mode" required horizontal
                     :options="$deliveryModes"
                     :selected="$supplier?->default_delivery_mode ?? 'to_office'"
                     :placeholder="false"
                     hint="Jobwork usually ships direct to port; trading goods come to the office to be repacked." />
    </div>
</x-ui.form-section>

{{-- =================== U–W · BANK DETAILS ======================= --}}
<x-ui.form-section title="Bank Details" icon="bi-bank"
                   subtitle="Where we remit their payment.">
    <div class="form-stack">

        {{-- Col U — dropdown of common banks; type to add a name not in the list. --}}
        @php
            $bankValue = old('bank_name', $supplier?->bank_name);
            $bankOptions = $banks ?? [];
            if (filled($bankValue) && ! array_key_exists($bankValue, $bankOptions)) {
                $bankOptions = [$bankValue => $bankValue] + $bankOptions;
            }
        @endphp
        <div class="row form-line">
            <label for="bank_name" class="col-sm-4 col-lg-3 col-form-label fw-semibold">Bank Name</label>
            <div class="col-sm-8 col-lg-9">
                <select id="bank_name" name="bank_name" data-searchable data-allow-create="true"
                        data-placeholder="Search or type bank name…"
                        class="form-select @error('bank_name') is-invalid @enderror">
                    <option value="">— Select —</option>
                    @foreach($bankOptions as $value => $label)
                        <option value="{{ $value }}" @selected((string) $bankValue === (string) $value)>{{ $label }}</option>
                    @endforeach
                </select>
                @error('bank_name')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">Pick from the list, or type a new bank name and press Enter.</div>
            </div>
        </div>

        {{-- Col V --}}
        <x-ui.field name="account_number" label="Account Number" :value="$supplier?->account_number"
                    horizontal maxlength="40" placeholder="50100123456789"
                    class="font-monospace" />

        {{-- Col W --}}
        <x-ui.field name="ifsc_code" label="IFSC Code" :value="$supplier?->ifsc_code"
                    horizontal maxlength="11" placeholder="HDFC0001234"
                    class="font-monospace text-uppercase" />

    </div>
</x-ui.form-section>

{{-- ====================== X–Y · AGENT =========================== --}}
<x-ui.form-section title="Agent" icon="bi-person-badge"
                   subtitle="Select from Agent Master only — pick the % or /pc rate from the list. No typing.">
    <div class="form-stack">

        {{-- Col X — "of supplier side selected in agent master should show
             here". Reloaded when the party type changes, because a jobber's
             agent comes from the jobber side. The list is a UI filter; the same
             rule is re-applied on submit from Supplier::AGENT_SIDES. --}}
        <x-ui.select name="agent_id" label="Agent" :options="$agents"
                     :selected="$supplier?->agent_id" horizontal searchable
                     placeholder="Search agent…"
                     data-cascade-parent="#party_type"
                     :data-cascade-url="route('masters.suppliers.agents')"
                     data-cascade-key="party_type"
                     :hint="count($agents) ? 'Missing an agent? Open Agent Master and create a supplier-side agent.' : 'No agents exist on this side yet.'" />

        {{-- Col Y — pick a rate from Agent Master (dropdown when several). --}}
        <div class="row form-line">
            <label for="agent_commission_pick" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                Agent Commission
            </label>
            <div class="col-sm-8 col-lg-9">
                <select id="agent_commission_pick"
                        class="form-select @error('agent_commission_value') is-invalid @enderror @error('agent_commission_type') is-invalid @enderror">
                    <option value="">— Select agent first —</option>
                </select>
                <input type="hidden" id="agent_commission_value" name="agent_commission_value"
                       value="{{ old('agent_commission_value', $supplier?->agent_commission_value) }}">
                <input type="hidden" id="agent_commission_type" name="agent_commission_type"
                       value="{{ old('agent_commission_type', $supplier?->agent_commission_type) }}">
                @error('agent_commission_value')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                @error('agent_commission_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text" id="agent-commission-hint">
                    Rates come from Agent Master. If an agent has more than one %, pick which one applies to this supplier.
                </div>
            </div>
        </div>

    </div>
</x-ui.form-section>

{{-- ====================== Z, AA · OTHER ========================= --}}
<x-ui.form-section title="Other Details" icon="bi-card-text">
    <div class="form-stack">

        {{-- Col Z --}}
        <x-ui.select name="status" label="Status" required horizontal
                     :options="['active' => 'Active', 'inactive' => 'Inactive']"
                     :selected="$supplier?->status ?? 'active'"
                     :placeholder="false" />

        {{-- Col AA --}}
        <x-ui.textarea name="remarks" label="Remarks" :value="$supplier?->remarks"
                       horizontal rows="2" placeholder="Optional notes" />

        <x-ui.textarea name="comments" label="Comments" :value="$supplier?->comments"
                       horizontal rows="2" placeholder="Optional comments" />

    </div>
</x-ui.form-section>

<div class="form-actions">
    <button type="submit" class="btn btn-primary px-4">
        <i class="bi bi-check-lg me-1"></i>{{ $supplier ? 'Update' : 'Save' }} Supplier
    </button>
    <a href="{{ route('masters.suppliers.index') }}" class="btn btn-outline-secondary">Cancel</a>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {

    /* ------------------------------------------------------------------ *
     * Conditional fields.
     *
     * The starting state is rendered by the server — see the top of this file.
     * What follows only reacts to the user changing the field each block
     * depends on, so nothing flashes into view and back out on load.
     *
     * Hidden, not disabled: a disabled input is still in the document but a
     * hidden one is what a user reads as "does not apply". Either way this is
     * a courtesy — SupplierRequest re-applies every one of these conditions
     * server-side, so a hand-posted GST number on an unregistered supplier is
     * dropped whatever the browser did.
     * ------------------------------------------------------------------ */

    /**
     * Which supplier types carry a GST number. Sent from the server rather
     * than hard-coded, because the sheet asks for the list to be extendable
     * and a type added next year has to answer this for itself.
     */
    const registeredTypes = @json($supplierTypeFlags);

    const supplierType = document.getElementById('supplier_type_id');
    const gstRow       = document.getElementById('gst-row');
    const gstInput     = document.getElementById('gst_number');
    const msmeToggle   = document.getElementById('is_msme');
    const msmeRow      = document.getElementById('msme-row');
    const partyType    = document.getElementById('party_type');
    const jobwork      = document.getElementById('jobwork-section');

    function show(element, visible) {
        element.classList.toggle('d-none', ! visible);
    }

    function applyGst() {
        const registered = registeredTypes[supplierType.value] === true;

        show(gstRow, registered);

        // Left visible when it holds a rejected value, so the error next to it
        // is not hidden along with the field it belongs to.
        if (! registered && ! gstInput.classList.contains('is-invalid')) {
            gstInput.value = '';
        }
    }

    function applyMsme() {
        show(msmeRow, msmeToggle.checked);
    }

    function applyJobwork() {
        show(jobwork, partyType.value === 'jobber' || partyType.value === 'both');
    }

    supplierType.addEventListener('change', applyGst);
    msmeToggle.addEventListener('change', applyMsme);
    partyType.addEventListener('change', applyJobwork);

    applyGst();
    applyMsme();
    applyJobwork();

    /* ------------------------------------------------------------------ *
     * Col L — other contact persons. Repeatable rows.
     * ------------------------------------------------------------------ */
    const rows     = document.getElementById('contact-rows');
    const template = document.getElementById('contact-row-template');
    const addBtn   = document.getElementById('add-contact');

    /**
     * Field names carry their row index, so a row added after one was removed
     * must not reuse an index still in the DOM — two inputs sharing
     * contacts[2][name] would silently drop one on submit.
     */
    function reindex() {
        rows.querySelectorAll('[data-contact-row]').forEach(function (row, index) {
            row.querySelectorAll('[name^="contacts"]').forEach(function (field) {
                field.name = field.name.replace(/contacts\[\d+\]/, 'contacts[' + index + ']');
            });
        });
    }

    rows.addEventListener('click', function (event) {
        const remove = event.target.closest('.js-remove-contact');
        if (! remove) return;

        const all = rows.querySelectorAll('[data-contact-row]');

        // Keep at least one row — an empty table has no affordance beyond the
        // button, and clearing the last row is the same outcome.
        if (all.length === 1) {
            all[0].querySelectorAll('input').forEach(function (field) { field.value = ''; });

            const select = all[0].querySelector('select');
            select?.tomselect ? select.tomselect.clear(true) : (select.value = '');
        } else {
            remove.closest('[data-contact-row]').remove();
        }

        reindex();
    });

    addBtn.addEventListener('click', function () {
        const index = rows.querySelectorAll('[data-contact-row]').length;
        const row   = template.content.cloneNode(true).querySelector('tr');

        row.querySelectorAll('[name*="__INDEX__"]').forEach(function (field) {
            field.name = field.name.replace('__INDEX__', index);
        });

        rows.appendChild(row);

        // The page-load sweep in app.js has already run, so a select added now
        // has to be upgraded here or it renders as a bare dropdown next to
        // three searchable ones.
        const select = row.querySelector('select[data-searchable]');
        if (select && typeof window.upgradeSearchableSelect === 'function') {
            window.upgradeSearchableSelect(select);
        }

        row.querySelector('input')?.focus();
    });

    /* ------------------------------------------------------------------ *
     * Secondary Contact Person toggle — hidden until asked for. Unchecking
     * resets the table to one blank row rather than leaving typed values
     * sitting in a hidden section that would still post on submit.
     * ------------------------------------------------------------------ */
    const secondaryToggle = document.getElementById('toggle-secondary-contacts');
    const secondaryWrap   = document.getElementById('secondary-contacts-wrap');

    secondaryToggle?.addEventListener('change', function () {
        secondaryWrap.classList.toggle('d-none', ! secondaryToggle.checked);

        if (secondaryToggle.checked) return;

        rows.querySelectorAll('[data-contact-row]').forEach(function (row, index) {
            if (index === 0) {
                row.querySelectorAll('input').forEach(function (field) { field.value = ''; });

                const select = row.querySelector('select');
                select?.tomselect ? select.tomselect.clear(true) : (select && (select.value = ''));
            } else {
                row.remove();
            }
        });
    });

    /* ------------------------------------------------------------------ *
     * "Tell me if a certain code is used already" (sheet col A).
     * A convenience only — the unique index is what actually enforces it.
     * ------------------------------------------------------------------ */
    const input    = document.getElementById('display_code');
    const feedback = document.querySelector('.js-code-feedback');
    const checkUrl = @json(route('masters.suppliers.check-code'));
    const ignoreId = @json($supplier?->id);
    const original = input.value.trim().toUpperCase();
    const resting  = feedback.textContent;
    let timer = null;

    function rest() {
        feedback.textContent = resting;
        feedback.className = 'form-text js-code-feedback';
    }

    input.addEventListener('input', function () {
        clearTimeout(timer);
        const value = input.value.trim().toUpperCase();

        // Unchanged on an edit form is not a clash with itself.
        if (value === '' || value === original) {
            input.classList.remove('is-invalid', 'is-valid');
            rest();
            return;
        }

        // Debounced so a 5-character code is one request, not five.
        timer = setTimeout(function () {
            const params = new URLSearchParams({ value: value });
            if (ignoreId) params.append('ignore', ignoreId);

            fetch(checkUrl + '?' + params, { headers: { 'Accept': 'application/json' } })
                .then(r => r.ok ? r.json() : Promise.reject())
                .then(function (data) {
                    input.classList.toggle('is-invalid', !data.available);
                    input.classList.toggle('is-valid', data.available);
                    feedback.textContent = data.available
                        ? 'Available.'
                        : 'Already used by another supplier — choose another.';
                    feedback.className = 'form-text js-code-feedback ' +
                        (data.available ? 'text-success' : 'text-danger');
                })
                // Network failure must not block the form. The unique index
                // still rejects a duplicate on submit.
                .catch(rest);
        }, 350);
    });

    /* ------------------------------------------------------------------ *
     * Agent commission — pick a rate from Agent Master (dropdown; no typing).
     * ------------------------------------------------------------------ */
    const agentSelect          = document.getElementById('agent_id');
    const commissionPick       = document.getElementById('agent_commission_pick');
    const agentCommissionValue = document.getElementById('agent_commission_value');
    const agentCommissionType  = document.getElementById('agent_commission_type');
    const agentCommissionHint  = document.getElementById('agent-commission-hint');
    const agentCommissions     = @json($agentCommissions ?? []);
    const savedCommissionValue = agentCommissionValue?.value || '';
    const savedCommissionType  = agentCommissionType?.value || '';

    function ratesFor(agentId) {
        if (! agentId) return [];
        const rows = agentCommissions[agentId] ?? agentCommissions[String(agentId)] ?? [];
        return Array.isArray(rows) ? rows : (rows ? [rows] : []);
    }

    function optionValue(row) {
        return row.type + '|' + String(row.value);
    }

    function fillHiddenFromPick() {
        if (! commissionPick || ! agentCommissionValue || ! agentCommissionType) return;
        const raw = commissionPick.value || '';
        if (! raw) {
            agentCommissionValue.value = '';
            agentCommissionType.value = '';
            return;
        }
        const parts = raw.split('|');
        agentCommissionType.value = parts[0] || '';
        agentCommissionValue.value = parts.slice(1).join('|') || '';
    }

    function rebuildCommissionPick(agentId, preferType, preferValue) {
        if (! commissionPick) return;

        const rates = ratesFor(agentId);
        commissionPick.innerHTML = '';

        if (! agentId) {
            commissionPick.appendChild(new Option('— Select agent first —', ''));
            commissionPick.disabled = true;
            fillHiddenFromPick();
            if (agentCommissionHint) {
                agentCommissionHint.textContent = 'Rates come from Agent Master. If an agent has more than one %, pick which one applies to this supplier.';
            }
            return;
        }

        if (rates.length === 0) {
            commissionPick.appendChild(new Option('— No rate on this agent —', ''));
            commissionPick.disabled = true;
            agentCommissionValue.value = '';
            agentCommissionType.value = '';
            if (agentCommissionHint) {
                agentCommissionHint.innerHTML = 'This agent has <strong>no % / pc rate</strong> in Agent Master (common for <strong>Supplier pays</strong>). Add a commission entry on the agent if needed.';
            }
            return;
        }

        commissionPick.disabled = false;
        if (rates.length > 1) {
            commissionPick.appendChild(new Option('— Select rate —', ''));
        }

        let matched = '';
        rates.forEach(function (row) {
            const value = optionValue(row);
            commissionPick.appendChild(new Option(row.label, value));
            if (preferType && preferValue !== '' && preferValue !== null
                && row.type === preferType
                && Number(row.value) === Number(preferValue)) {
                matched = value;
            }
        });

        if (matched) {
            commissionPick.value = matched;
        } else if (rates.length === 1) {
            commissionPick.value = optionValue(rates[0]);
        } else {
            commissionPick.value = '';
        }

        fillHiddenFromPick();

        if (agentCommissionHint) {
            agentCommissionHint.textContent = rates.length > 1
                ? 'This agent has more than one rate — pick which % or /pc applies to this supplier.'
                : 'Taken from Agent Master for this agent.';
        }
    }

    function onAgentChanged(agentId) {
        rebuildCommissionPick(agentId, null, null);
    }

    function bindAgentCommission() {
        if (! agentSelect) return;

        if (! agentSelect.dataset.commissionNativeBound) {
            agentSelect.dataset.commissionNativeBound = '1';
            agentSelect.addEventListener('change', function () {
                onAgentChanged(agentSelect.value);
            });
        }

        function attachTomSelect() {
            if (! agentSelect.tomselect || agentSelect.dataset.commissionTsBound) return;
            agentSelect.dataset.commissionTsBound = '1';
            agentSelect.tomselect.on('change', function (value) {
                onAgentChanged(value);
            });
        }

        attachTomSelect();
        setTimeout(attachTomSelect, 50);

        commissionPick?.addEventListener('change', fillHiddenFromPick);

        // Edit / validation old(): keep saved rate selected when possible.
        rebuildCommissionPick(agentSelect.value, savedCommissionType, savedCommissionValue);
    }

    bindAgentCommission();
});
</script>
@endpush
